spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_com_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      open-in-view: true
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false